name: desc-stack prod

on: 
  push:
    branches:
      - prod

jobs:
  build:
    name: desc-stack prod
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: pull dev
        run: docker pull lsstdesc/stack-jupyter:dev
      - name: Docker tag prod
        run: docker tag lsstdesc/stack-jupyter:dev lsstdesc/stack-jupyter:prod
      - name: Docker push prod
        run: docker push lsstdesc/stack-jupyter:prod
       
