name: desc-stack-old

on: 
  push:
    branches:
      - old

jobs:
  build:
    name: desc-stack-old
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: pull requested image
        run: docker pull lsstdesc/stack-jupyter:prod
      - name: Docker tag requested image as old
        run: docker tag lsstdesc/stack-jupyter:prod lsstdesc/stack-jupyter:old
      - name: Docker push old
        run: docker push lsstdesc/stack-jupyter:old
