name: desc-stack-weekly latest

on:
  schedule:
    - cron: '15 23 * * 5'
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v2
        with:
          ref: weekly
          fetch-depth: 1
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name : Get weekly number and date 
        run: |
          echo "LSST_TAG=w_$(date "+%Y")_$(date "+%U" -d "$end_date-3 days")" >> $GITHUB_ENV
          echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV
      - name: tag current weekly
        run: |
          docker pull lsstdesc/stack-jupyter:weekly-latest
          docker run --rm lsstdesc/stack-jupyter:weekly-latest /bin/bash -c "source /opt/lsst/software/stack/loadLSST.bash"
          if $?; then
            echo "No functional weekly-latest with lsst_distrib available"
          else
            docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/stack-jupyter:weekly
            docker push lsstdesc/stack-jupyter:weekly
          fi
        #continue-on-error: true
      - name: do docker build
        run: docker build --no-cache --build-arg LSST_TAG=${{env.LSST_TAG}} -t lsstdesc/stack-jupyter:weekly-latest -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: test supreme
        run: docker run --rm lsstdesc/stack-jupyter:weekly-latest /bin/bash -c "source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && python -c 'import pyccl'"
      - name: Docker push
        run: docker push lsstdesc/stack-jupyter:weekly-latest
      - name: tag versions
        run: |
          docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/stack-jupyter:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker push lsstdesc/stack-jupyter:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/stack-jupyter:${{env.LSST_TAG}}
          docker push lsstdesc/stack-jupyter:${{env.LSST_TAG}}
          docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/desc-stack:weekly-latest
          docker push lsstdesc/desc-stack:weekly-latest
          docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/desc-stack:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker push lsstdesc/desc-stack:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker tag lsstdesc/stack-jupyter:weekly-latest lsstdesc/desc-stack:${{env.LSST_TAG}}
          docker push lsstdesc/desc-stack:${{env.LSST_TAG}}
  
       
