name: desc-stack release

on: 
 release:
  types: [published]

jobs:
  build:
    name: desc-stack release
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=DOCKTAG::${GITHUB_REF/refs\/tags\//}
      - name: do docker build
        run: docker build --no-cache -t heather999/jupyter-test:${{ steps.get_tag.outputs.DOCKTAG }} -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push tag
        run: docker push  heather999/jupyter-test:${{ steps.get_tag.outputs.DOCKTAG }}
      - name: tag dev
        run: docker tag heather999/jupyter-test:${{ steps.get_tag.outputs.DOCKTAG }} heather999/jupyter-test:dev
      - name: Docker push dev
        run: docker push heather999/jupyter-test:dev
       
