name: desc-stack rollback

on: 
  push:
    branches:
      - rollback

jobs:
  build:
    name: desc-stack rollback
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: pull requested image
        run: docker pull lsstdesc/stack-jupyter:dev
      - name: Docker tag requested image as prod
        run: docker tag lsstdesc/stack-jupyter:dev lsstdesc/stack-jupyter:prod
      - name: Docker push prod
        run: docker push lsstdesc/stack-jupyter:prod
