name: desc-stack-weekly latest

on:
  push:
    branches: 
      - weekly
  

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/stack-jupyter:weekly-latest -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: test supreme
        run: docker run --rm lsstdesc/stack-jupyter:weekly-latest /bin/sh -c "source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && python -c 'import supreme'"
      - name: Docker push
        run: docker push lsstdesc/stack-jupyter:weekly-latest
       
